version: "2"
services:
  kserver:
    image: raulbaena/k18:kserver
    volumes: 
      - "krb5data:/var/kerberos"
    networks:
      - mynet
  sshd:
    image: raulbaena/k18:sshd
    networks:
      - mynet     
  portainer:
    image: portainer/portainer
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mynet   
networks:
 mynet:
volumes: 
 krb5data:
