version: "3"
services:
  kserver:
    image: raulbaena/k18:kserver
    deploy:
      replicas: 3
    networks:
      - mynet
  sshd:
    image: raulbaena/k18:sshd
    networks:
      - mynet     
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mynet 
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "50000:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - mynet 
networks:
 mynet:

